### PR TITLE
Upgraded flutter_map dependency to 0.11.0

### LINKED ISSUE #23: Conflict to actual flutter_map version
Hi, when upgrading flutter_map to version 0.11.0 I get this error:

> Because flutter_map_tappable_polyline 1.2.0 depends on flutter_map ^0.10.1+1 and no versions of flutter_map_tappable_polyline match >1.2.0 <2.0.0, flutter_map_tappable_polyline ^1.2.0 requires flutter_map ^0.10.1+1.

Is there something I made wrong or do you need to add the compatibility?

### PR DESCRIPTION
**Pull request by S-Man42**
Close #23

### CODE REVIEW

**Comment by tuarrep** [comment]
Is there any chance to be less strict on the version constraint and accept any 0.x version?

If not lgtm

**Comment by S-Man42** [comment]
You can do: 
`>=0.11.0 <1.0.0`

or even (which is not recommended)
`any`

**Comment by HugoHeneault** [comment]
As even 0.x minor version update might include breaking changes I prefer to keep the PR like this. 

See https://dart.dev/tools/pub/versioning#semantic-versions

> Although semantic versioning doesn’t promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to 0.1.2+1 indicates a change that doesn’t affect the public API. 

Thanks @S-Man42, I'm reviewing it right now.

**Comment by HugoHeneault** [comment]
All good! Thanks @S-Man42

**Pull request merged**
