### PR TITLE
Migrate to flutter_map v5

### LINKED ISSUE #52: Update to flutter_map v4
https://pub.dev/packages/flutter_map/versions/4.0.0-dev.1/changelog incoming. 

Any help appreciated as we don't have much time to do migration these days. 

Will try to get some time but can't do any promise, given the time needed to merge #51 😬

### PR DESCRIPTION
**Pull request by JaffaKetchup**
Closes #52.
Replaces #53 (with thanks to @azaderdogan for most of the work in here :)).

### CODE REVIEW

**Comment by azaderdogan** [comment]
> Closes #52. Replaces #53 (with thanks to @azaderdogan for most of the work in here :)).

You are welcome :)

**Comment by HugoHeneault** [comment]
Awesome, reviewing it and merging asap. Thanks alot guys!

**Comment by HugoHeneault** [comment]
Working good, cleaner than before, great job!

**Comment by HugoHeneault** [comment]
Merged & released v5 🥳 

Thanks again guys! Can't wait to test v5 in my apps!

**Pull request merged**
