### PR TITLE
Migrate to null safety

### LINKED ISSUE #26: Null safety
Would be nice to see it in null safety

### PR DESCRIPTION
**Pull request by sbu-WBT**
fixes #26

### CODE REVIEW

**Comment by barbalex** [comment]
There is a null safe version of flutter_map published now (0.13.0) but there is a major bug that causes the map to crash as soon as you move/rotate: https://github.com/fleaflet/flutter_map/pull/923

**Comment by barbalex** [comment]
flutter_map has released v0.13.1 that solves the remaining issue.

**Comment by tuarrep** [comment]
Thank you, @sbu-WBT and @barbalex 🙏 
I'll have a look this night and test it tomorrow

**Comment by tuarrep** [comment]
Code LGTM,

@HugoHeneault could you have a look?

**Comment by HugoHeneault** [comment]
Thanks guys!
Looking on it this afternoon & publishing if all's fine

**Comment by HugoHeneault** [comment]
Awesome! Thanks a lot @sbu-WBT 👏

**Pull request merged**
