### PR TITLE
Migrate to flutter_map v3

### PR DESCRIPTION
**Pull request by Cteq3132**
This PR is in anticipation of the new v3 version of flutter_map. I tried it with 3.0.0-beta.3 and it works ok.

### CODE REVIEW

**Comment by MaxiStefan** [comment]
Hi, I also did something similar locally while using 3.0.0-beta.3 flutter_map and I have encountered problems with the onTap callback of the polyline when other layers such as polygons are present on the map. I have used your code and the problem persists. Can you reproduce it?

**Comment by Cteq3132** [comment]
Hey ! 
I will look into this and keep you updated

**Comment by Cteq3132** [comment]
Hi @MaxiStefan, does this happened when using multiple layers of `FlutterMap`? If this is the case, I think this migration to `FlutterMap` v3 isn't a regression because I manage to reproduce your problem with the code on the master branch. Maybe we should deal with this issue in another PR? 

I simply try the following example with the data of the `example` folder:

<details>
  <summary>Reproductible example</summary>

```dart
FlutterMap(
        options: MapOptions(
          plugins: [
            TappablePolylineMapPlugin(),
          ],
          center: LatLng(45.1313258, 5.5171205),
          zoom: 11.0,
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            subdomains: ['a', 'b', 'c'],
          ),
          TappablePolylineLayerOptions(
              polylines: [
                TaggedPolyline(
                  tag: 'My Polyline',
                  // An optional tag to distinguish polylines in callback
                  points: getPoints(0),
                  color: Colors.red,
                  strokeWidth: 9.0,
                ),
              ],
              onTap: (polylines, tapPosition) => print('Tapped: ' +
                  polylines.map((polyline) => polyline.tag).join(',') +
                  ' at ' +
                  tapPosition.globalPosition.toString()),
              onMiss: (tapPosition) {
                print('No polyline was tapped at position ' +
                    tapPosition.globalPosition.toString());
              }),
          TappablePolylineLayerOptions(
            // Will only render visible polylines, increasing performance
            polylineCulling: true,
            pointerDistanceTolerance: 20,
            polylines: [
              TaggedPolyline(
                tag: 'My 2nd Polyline',
                // An optional tag to distinguish polylines in callback
                points: getPoints(1),
                color: Colors.black,
                strokeWidth: 3.0,
              ),
            ],
            onTap: (polylines, tapPosition) => print('Tapped: ' +
                polylines.map((polyline) => polyline.tag).join(',') +
                ' at ' +
                tapPosition.globalPosition.toString()),
            onMiss: (tapPosition) {
              print('No polyline was tapped at position ' +
                  tapPosition.globalPosition.toString());
            },
          )
        ],
      )
```
</details>

**Comment by hardikJoshi123** [comment]
I think this PR should be merged. Thanks!

**Comment by MaxiStefan** [comment]
Hi @Cteq3132 indeed I do. I have all 3 layers, MarkeyLayer, PolylineLayer and PolygonLayer all active almost all the time. Do you have any progress on finding the problem?

**Comment by S-Man42** [comment]
please upgrade the plugin!

**Comment by jean-gblr** [comment]
Hello my friend, could you please upgrade this plugin if all is correct ? :D

**Comment by HugoHeneault** [comment]
Thanks alot for your help and time. We've merged #51

**Pull request closed without merging**
