### PR TITLE
Flutter map 1.0.0 support

### PR DESCRIPTION
**Pull request by zeitspacetyler**
- Fixes type and function signature mismatches
- Minor update to the README
- Updates flutter_map dependancy to 1.0.0

### CODE REVIEW

**Review by tuarrep — APPROVED** [review]
LGTM @HugoHeneault

**Comment by S-Man42** [comment]
Any chance to release it?

**Comment by HugoHeneault** [comment]
I'm testing it right now :)

**Review by HugoHeneault — APPROVED** [review]
LGTM :) Thanks for this update!

**Comment by HugoHeneault** [comment]
3.2.0 just got published. 

https://pub.dev/packages/flutter_map_tappable_polyline

**Pull request merged**
